---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: go-hello-http
    repoURL: https://github.com/ironcore864/openstream-gitops-test/charts/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
